"""Run the unchanged published reference engine and its required SfM stage.
Upstream can return exit 0 on failure, so outputs/completion text are checked.
No substitution of the former custom rotation/translation fit is permitted.
"""
import hashlib,json,math,os,re,subprocess,time
from pathlib import Path
from sfm import run_sfm

ROOT=Path('/data');OUT=ROOT/'output';IMAGE='ulong2/ie_kalibr_image@sha256:2de8ac994a86951b6255e4b8485eae9982ea3ed03bac33dd9d0ee254e383587c'
engine=Path('/home/iKalibr/install/lib/ikalibr/ikalibr_prog')
env={**os.environ,'LIBGL_ALWAYS_SOFTWARE':'1','QT_QPA_PLATFORM':'offscreen'}
def engine_run(label):
    log=ROOT/(label+'.log')
    with log.open('w') as output:
        process=subprocess.Popen(['xvfb-run','-a','-s','-screen 0 1280x720x24 +extension GLX','roslaunch','ikalibr','ikalibr-prog.launch','config_path:=/data/config.yaml'],stdout=output,stderr=subprocess.STDOUT,env=env,start_new_session=True)
        began=time.monotonic()
        while process.poll() is None:
            contents=log.read_text(errors='replace')
            if 'solving and outputting finished' in contents or 'images have been output to' in contents:
                # Parameters are flushed before the completion message; close the
                # optional viewer using a process-group signal, not a fabricated success.
                import signal
                os.killpg(process.pid,signal.SIGTERM);process.wait(timeout=20);break
            if time.monotonic()-began>900:
                import signal
                os.killpg(process.pid,signal.SIGTERM);process.wait(timeout=20);raise ValueError('Reference processing timed out. The capture is kept.')
            time.sleep(.5)
    return log.read_text(errors='replace')
stage=os.environ.get('GAITTRACE_REFERENCE_STAGE','all')
if stage not in ['all','prepare','finish']:raise ValueError('Invalid processor stage.')
prepared=list(OUT.rglob('sfm_ws'))
# An immutable upload may be retried after a processor interruption. Reuse only
# upstream-written images/info from that job, never fabricate poses or matches.
contents='' if len(prepared)==1 and (prepared[0].parent/'info.json').is_file() else engine_run('reference-initial')
params=OUT/'ikalibr_param.json'
if params.exists() and (ROOT/'reference-final.log').is_file():contents=(ROOT/'reference-final.log').read_text(errors='replace')
if not params.exists():
    # Paths are generated by upstream from our fixed topic/configuration. Do not
    # execute an uploaded shell script or accept arbitrary paths from phone files.
    bases=list(OUT.rglob('sfm_ws'))
    if len(bases)!=1:raise ValueError('Reference initialization could not track this scene. The capture is kept.')
    sfm=bases[0];images=sfm.parent/'images' if (sfm.parent/'images').is_dir() else sfm.parent
    matches=sfm/'matches.txt'
    if not images.is_dir() or not matches.is_file():raise ValueError('Reference scene preparation was incomplete.')
    provenance=json.loads((ROOT/'provenance.json').read_text());K=provenance['metadata']['lensProfile']['lens']['cameraMatrix']
    camera=','.join(str(v) for v in [K[0][0],K[1][1],K[0][2],K[1][2]])
    info=json.loads((sfm.parent/'info.json').read_text())['info']['images']
    ordered=[r['value'] for r in sorted(info,key=lambda r:r['key'])]
    if any(not re.fullmatch(r'[0-9]+\.jpg',name) for name in ordered):raise ValueError('Invalid upstream image list.')
    selected=ordered[::max(1,math.ceil(len(ordered)/200))]
    if len(selected)<100:raise ValueError('Not enough reference images.')
    image_list=ROOT/'sfm-images.txt';image_list.write_text('\n'.join(selected)+'\n')
    # Bounded SfM keyframes are real measurements, not interpolated/generated
    # images. All original frames and continuous IMU remain in the capture/bag.
    plan={'workspace':str(sfm.relative_to(ROOT)),'images':str(images.relative_to(ROOT)),'cameraParameters':camera,'measuredKeyframes':len(selected)}
    (ROOT/'sfm-stage.json').write_text(json.dumps(plan,indent=2))
    if stage=='prepare':raise SystemExit(0)
    if stage=='all':run_sfm(gpu=False)
    elif not (ROOT/'sfm-complete.json').is_file() or not all((sfm/name).is_file() for name in ['cameras.txt','images.txt','points3D.txt']):raise ValueError('External SfM did not complete.')
    contents=engine_run('reference-final')
if not params.exists() or 'solving and outputting finished' not in contents:raise ValueError('Reference calibration did not complete. The capture is kept.')
raw=json.loads(params.read_text());provenance=json.loads((ROOT/'provenance.json').read_text());meta=provenance['metadata']
sfm_evidence=json.loads((ROOT/'sfm-complete.json').read_text())
# Keep original upstream conventions and all raw results. Admission to metric
# tracking is separate; this bridge does not invent a Kalibr/OpenVINS noise model
# or certify a camera/IMU lever arm from a successful executable return.
result={'schemaVersion':1,'kind':'phone-reference-camera-imu-calibration-v1','method':'ikalibr-tro-2025','status':'reference-solved-review-required',
 'sourceSha256':provenance['sourceSha256'],'binding':{k:meta[k] for k in ['installationId','captureId','cameraId','width','height','imageAxes','sensorOrientationDegrees','stabilizationRequested','capturePipeline','opticalSetup']},
 'lensProfile':meta['lensProfile'],'software':{'image':IMAGE,'executableSha256':hashlib.sha256(engine.read_bytes()).hexdigest()},
 'upstreamParameters':raw,'cameraImuCandidateReady':False,'fullCalibrationReady':False,'distanceReady':False,'independentDistanceValidation':False,
 'reviewRequired':['parameter-conventions-and-physical-bounds','repeatability-and-residuals','complete-noise-model','independent-distance-validation'],
 'provenance':{**{k:v for k,v in provenance.items() if k!='metadata'},'sfm':sfm_evidence}}
(ROOT/'result.json').write_text(json.dumps(result,indent=2))
