apply plugin: 'com.android.library'

group = 'expo.modules.gaitrecording'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(':expo-modules-core').projectDir.absolutePath, 'ExpoModulesCorePlugin.gradle')
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()

android {
  namespace 'expo.modules.gaitrecording'
}

dependencies {
  implementation 'com.google.android.gms:play-services-fitness:21.3.0'
}
