from pathlib import Path
import html

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'reports' / 'DATA_SUFFICIENCY_AND_PUBLIC_SOURCE_REVIEW.html'

rows = [
    ('Binary research prototype', 'YES — sufficient to proceed', '314 pooled participants; 126 healthy and 188 stroke; participant-disjoint internal validation plus RevalExo external testing.', 'This supports continued model development and reproducible benchmarking.', 'Do not inflate the evidence by counting windows as independent subjects.'),
    ('Age-stratified stroke classifier', 'NO — metadata gap', 'Age bands exist for parts of the wider Voisard release, but current binary labels are not evenly represented: no CVA in the young band and limited healthy/stroke pairing by age.', 'Run descriptive age coverage and age-confounding analysis only.', 'Need linked individual age for both healthy and stroke groups in each intended band.'),
    ('Sex-stratified performance', 'NO — incomplete linkage', 'Some sources have sex information, but it is not consistently linked to the complete modeling/evaluation tables.', 'Report available cohort summaries; do not claim fairness or parity.', 'Need subject-level sex labels and adequate sample size per class/sex cell.'),
    ('Stroke severity/generalisation', 'PARTIAL', 'Zhou adds 10 stroke participants with ages 37–88 and FAC 1–5, but no healthy controls and repeated rehabilitation visits.', 'Use for auxiliary severity or longitudinal analysis with participant-level grouping.', 'It should not be pooled as new binary healthy/stroke training data.'),
    ('Stroke-specific clinical discrimination', 'NO — control gap', 'The current healthy controls do not test whether the model confuses stroke with Parkinson’s, MS, fracture, COPD, or other mobility impairment.', 'Treat current model as stroke-versus-healthy, not stroke-specific.', 'Add non-stroke clinical cohorts for specificity testing.'),
    ('Independent wearable-IMU validation', 'PARTIAL', 'RevalExo provides a useful independent test, but only 17 participants.', 'Keep it locked and report uncertainty.', 'A second independent stroke+healthy wearable-IMU cohort would materially strengthen the claim.'),
]

sources = [
    ('Mobilise-D CVS', '2400 participants across PD, MS, proximal femoral fracture, and COPD cohorts; processed back-worn digital mobility outcomes.', 'High value for non-stroke clinical specificity and population robustness.', 'Not a direct drop-in training source: current public release is processed DMO data rather than the same bilateral LB/LF/RF raw tensor format.', 'Download a manageable subset after checking license, labels, and whether the released signals support a valid common representation.'),
    ('Mobilise-D TVS / technical validation', 'Healthy older adults plus PD, MS, COPD, fracture, and CHF-related cohorts; wearable sensor recordings and gold standards.', 'Best conceptual match for clinical specificity and older-adult coverage.', 'Channel placement and released format must be audited before pooling; it is not a stroke dataset.', 'Prioritise as an exclusion/specificity evaluation set, not binary training by default.'),
    ('Zhou stroke rehabilitation', '10 stroke participants; wearable IMU; ages 37–88; FAC 1–5; repeated visits.', 'Useful for severity, recovery, and longitudinal robustness.', 'No healthy controls; repeated visits create leakage risk; not suitable as ordinary binary training data.', 'Keep as stroke-only auxiliary/holdout evaluation.'),
    ('Triaxial healthy reference', '60 healthy participants; ages 65–88.', 'Useful older-healthy domain and age reference.', 'No bilateral LB/LF/RF configuration, so direct classifier scoring would require invalid channel fabrication.', 'Use for domain analysis or self-supervised pretraining only.'),
    ('PiG / multimodal clinical gait references', 'Healthy and stroke cohorts with motion capture, force, EMG, or related modalities.', 'Useful for construct validity and clinical feature hypotheses.', 'Not compatible with the current wearable-IMU input representation.', 'Do not pool; use for interpretation and external construct comparison.'),
]

def e(x): return html.escape(str(x))

out = """<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Data Sufficiency and Public Source Review</title><style>
body{font-family:Segoe UI,Arial,sans-serif;background:#f5f7fb;color:#172033;margin:0;padding:30px}.wrap{max-width:1500px;margin:auto}.hero{background:#102a43;color:#fff;padding:28px 32px;border-radius:14px}.hero h1{margin:0 0 8px;font-size:29px}.hero p{margin:0;color:#d7e7f3}.decision{margin:18px 0;padding:18px 22px;background:#e8f6f7;border-left:6px solid #0f8b8d;border-radius:8px;line-height:1.5}.section{margin-top:24px}.section h2{color:#102a43}.box{background:#fff;border:1px solid #dce4ed;border-radius:12px;overflow:auto;box-shadow:0 2px 8px #17203312}table{border-collapse:collapse;width:100%;min-width:1250px}th{background:#173f5f;color:#fff;text-align:left;padding:12px;font-size:13px}td{padding:12px;border-bottom:1px solid #e6ebf1;vertical-align:top;line-height:1.4;font-size:13px}tr:nth-child(even){background:#f8fafc}.status{font-weight:700;white-space:nowrap}.yes{color:#087f5b}.partial{color:#9a6700}.no{color:#b42318}.foot{font-size:12px;color:#5b6b7f;margin-top:14px}.source-note{font-size:13px;color:#4b5b70}.link{color:#075985}
</style></head><body><div class='wrap'><div class='hero'><h1>Data Sufficiency and Public Source Review</h1><p>Gate 1 of the improvement sequence: decide what the present data can support before adding experiments or datasets.</p></div><div class='decision'><strong>Decision:</strong> The current data is enough to continue developing and benchmarking a research prototype. It is not enough for reliable age/sex subgroup claims or a clinical-ready stroke-specific model. The next data acquisition should target clinical specificity and metadata, not simply more windows from another incompatible source.</div><div class='section'><h2>Current evidence sufficiency</h2><div class='box'><table><thead><tr><th>Claim or capability</th><th>Gate</th><th>Evidence currently available</th><th>What we can do now</th><th>What remains missing</th></tr></thead><tbody>"""
for claim, gate, evidence, now, missing in rows:
    cls = 'yes' if gate.startswith('YES') else ('partial' if gate.startswith('PARTIAL') else 'no')
    out += f"<tr><td><strong>{e(claim)}</strong></td><td class='status {cls}'>{e(gate)}</td><td>{e(evidence)}</td><td>{e(now)}</td><td>{e(missing)}</td></tr>"
out += """</tbody></table></div></div><div class='section'><h2>Public-source shortlist</h2><p class='source-note'>A source is not recommended for pooling merely because it contains gait data. Input channels, labels, participant independence, and clinical meaning must be compatible first.</p><div class='box'><table><thead><tr><th>Source</th><th>What it provides</th><th>Best role</th><th>Compatibility limitation</th><th>Recommended action</th></tr></thead><tbody>"""
for source, provides, role, limitation, action in sources:
    out += f"<tr><td><strong>{e(source)}</strong></td><td>{e(provides)}</td><td>{e(role)}</td><td>{e(limitation)}</td><td>{e(action)}</td></tr>"
out += """</tbody></table></div></div><p class='foot'>This review preserves the current pooled benchmark as the baseline. “Sufficient” means sufficient for the stated research claim, not sufficient for clinical deployment.</p></div></body></html>"""
OUT.write_text(out, encoding='utf-8')
print(OUT)
