from pathlib import Path
import html
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
coverage = pd.read_csv(ROOT / 'data/processed/age_group_label_availability.csv')
results = pd.read_csv(ROOT / 'data/processed/age_stratified_gait_results.csv')
summary = results[results.probability_type.eq('raw')].groupby('age_group').agg(participant_rows=('participants','sum'), folds=('fold','nunique'), mean_auroc=('roc_auc','mean'), mean_ba=('balanced_accuracy','mean')).reset_index()
def esc(x): return html.escape(str(x))
cov_rows = ''.join(f'<tr><td>{esc(r.age_group)}</td><td>{esc(r.label)}</td><td>{int(r.participants)}</td></tr>' for _, r in coverage.iterrows())
result_rows = ''.join(f'<tr><td>{esc(r.age_group)}</td><td>{int(r.participant_rows)}</td><td>{int(r.folds)}</td><td>{r.mean_auroc:.3f}</td><td>{r.mean_ba:.3f}</td></tr>' for _, r in summary.iterrows())
html_text = f'''<!doctype html><html><head><meta charset="utf-8"><title>Demographic Subgroup Validation Gate</title><style>body{{font-family:Segoe UI,Arial;background:#f5f7fb;color:#172033;margin:30px}}.wrap{{max-width:1200px;margin:auto}}.hero{{background:#102a43;color:#fff;padding:26px 30px;border-radius:14px}}.decision{{background:#fff4d6;border-left:6px solid #d99000;padding:18px;margin:18px 0;line-height:1.5}}.box{{background:#fff;border:1px solid #dce4ed;border-radius:12px;overflow:auto;margin:18px 0}}table{{border-collapse:collapse;width:100%}}th{{background:#173f5f;color:#fff;text-align:left;padding:12px}}td{{padding:12px;border-bottom:1px solid #e5eaf0}}tr:nth-child(even){{background:#f8fafc}}.bad{{color:#b42318;font-weight:700}}.ok{{color:#087f5b;font-weight:700}}</style></head><body><div class="wrap"><div class="hero"><h1>Demographic Subgroup Validation Gate</h1><p>Current evidence for age-stratified stroke-versus-healthy performance.</p></div><div class="decision"><strong>Decision: NOT READY for age-generalisation claims.</strong><br>The 18–39 band has 0 stroke participants; 40–59 has 27 stroke and 15 healthy participants; 60+ has 22 stroke and 15 healthy participants. Results are exploratory only.</div><h2>Label coverage</h2><div class="box"><table><tr><th>Age band</th><th>Label</th><th>Participants</th></tr>{cov_rows}</table></div><h2>Exploratory results</h2><div class="box"><table><tr><th>Age band</th><th>Participant rows across folds</th><th>Folds</th><th>Mean AUROC</th><th>Mean balanced accuracy</th></tr>{result_rows}</table></div><div class="box"><table><tr><th class="ok">Can report</th><th class="bad">Cannot report</th></tr><tr><td>Age coverage is uneven and should be treated as a confounder.</td><td>No young-stroke performance, fairness claim, or clinical age-generalisation claim.</td></tr><tr><td>Age-adjusted feature analyses and descriptive plots.</td><td>High AUROC in tiny subgroups as proof of robustness.</td></tr></table></div><h2>Required next data</h2><p>Link subject-level age for both healthy and stroke participants across the intended age bands. A practical minimum is 20–30 participants per class per band for exploratory estimates, with larger samples for confirmatory claims.</p></div></body></html>'''
out = ROOT / 'reports/DEMOGRAPHIC_SUBGROUP_VALIDATION_GATE.html'
out.write_text(html_text, encoding='utf-8')
print(out)
